name: Release Service

on:
  push:
    tags: "1.*"

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 14

    - run: npm ci

    - name: Get current time
      uses: MyJetTools/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm:ss
        utcOffset: "+00:00"

    - name: Check Service dir
      run: ls .

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/tags/})"
      id: extract_branch

    - name: Publish image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        path: .
        registry: docker.pkg.github.com
        repository: ${{ secrets.ORG_NAME }}/web.simple.timelock.admin/web.simple.timelock.admin
        tag_with_ref: true
        build_args: app_version=web.simple.timelock.admin:${{ steps.extract_branch.outputs.branch }},app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

    - name: Publish image ST
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ST_DOCKER_USER }}
        password: ${{ secrets.ST_DOCKER_PASSWORD }}
        path: .
        registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        repository: spot/web.simple.timelock.admin
        tag_with_ref: true
        build_args: app_version=web.simple.timelock.admin:${{ steps.extract_branch.outputs.branch }},app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

  update_version:
    needs: build
    runs-on: self-hosted
    steps:
    - name: get uat kube yamls
      uses: actions/checkout@v2
      with:
        repository: MyJetWallet/kubernates-infrastructure
        ref: uat        
        token: ${{ secrets.UAT_GIT_TOKEN }}
    - run: |
        pattern=web.simple.timelock.admin:.*$
        imagename=web.simple.timelock.admin:${GITHUB_REF#refs/tags/}
        reg=$"s/${pattern}/${imagename}/g"
        echo $reg
        find . -type f -name "deployment.*" -print0 -exec sed -i -r $reg {} \;
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -a -m "Update version of service web.simple.timelock.admin"
        git push